version: "3.9"

services:
  qt-api:
    build: ./backend
    container_name: qt-fleetcontrol-api
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - traccar-01_default

  qt-frontend:
    build:
      context: ./frontend
      args:
        VITE_AUTH_DISABLED: ${VITE_AUTH_DISABLED}
        VITE_API_BASE: ${VITE_API_BASE}
    container_name: qt-fleetcontrol-frontend
    env_file: .env
    ports:
      - "8083:80"
    networks:
      - traccar-01_default
networks:
  traccar-01_default:
    external: true
