version: "3.9"

services:
  qt-api:
    build: ./backend
    container_name: qt-fleetcontrol-api
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - traccar-01_default
    depends_on:
      - nominatim

  qt-frontend:
    build:
      context: ./frontend
      args:
        VITE_AUTH_DISABLED: ${VITE_AUTH_DISABLED}
        VITE_API_BASE: ${VITE_API_BASE}
    container_name: qt-fleetcontrol-frontend
    env_file: .env
    ports:
      - "8083:80"
    networks:
      - traccar-01_default

  nominatim:
    image: mediagis/nominatim:4.4
    container_name: qt-nominatim
    environment:
      PBF_URL: https://download.geofabrik.de/europe/austria-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/austria-updates/
      REPLICATION_UPDATE_INTERVAL: "604800"
      THREADS: "4"
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
      - nominatim-flatnode:/nominatim/flatnode
    ports:
      - "8085:8080"
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - traccar-01_default
networks:
  traccar-01_default:
    external: true

volumes:
  nominatim-data:
  nominatim-flatnode:
