version: "3.9"

services:
  qt-api:
    build: ./backend
    container_name: qt-fleetcontrol-api
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - traccar-01_default

  qt-frontend:
    build: ./frontend
    container_name: qt-fleetcontrol-frontend
    env_file: .env
    ports:
      - "8080:80"
    networks:
      - traccar-01_default
